/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(lfm_on_trigger.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6bd8bf7fd2f00168028fbc2b1b95383d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lfm_experimental/lfm_on_trigger.h>
// pydoc.h is automatically generated in the build directory
#include <lfm_on_trigger_pydoc.h>

void bind_lfm_on_trigger(py::module& m)
{

    using lfm_on_trigger    = gr::lfm_experimental::lfm_on_trigger;


    py::class_<lfm_on_trigger, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<lfm_on_trigger>>(m, "lfm_on_trigger", D(lfm_on_trigger))

        .def(py::init(&lfm_on_trigger::make),
           D(lfm_on_trigger,make)
        )
        



        ;




}








