/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(LFM_Source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e6b522c5b8a98efa109ddb5a6407e5f9)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lfmTools/LFM_Source.h>
// pydoc.h is automatically generated in the build directory
#include <LFM_Source_pydoc.h>

void bind_LFM_Source(py::module& m)
{

    using LFM_Source = ::gr::lfmTools::LFM_Source;


    py::class_<LFM_Source,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<LFM_Source>>(m, "LFM_Source", D(LFM_Source))

        .def(py::init(&LFM_Source::make),
             py::arg("bandwidth") = 2.0E+5,
             py::arg("duty_cycle") = 0.5,
             py::arg("pri") = 5.0000000000000001E-4,
             py::arg("samp_rate") = 2.0E+6,
             py::arg("amplitude") = 0.5,
             D(LFM_Source, make))


        .def("set_bandwidth",
             &LFM_Source::set_bandwidth,
             py::arg("bandwidth"),
             D(LFM_Source, set_bandwidth))


        .def("set_duty_cycle",
             &LFM_Source::set_duty_cycle,
             py::arg("duty_cycle"),
             D(LFM_Source, set_duty_cycle))


        .def("set_pri", &LFM_Source::set_pri, py::arg("pri"), D(LFM_Source, set_pri))


        .def("set_samp_rate",
             &LFM_Source::set_samp_rate,
             py::arg("samp_rate"),
             D(LFM_Source, set_samp_rate))


        .def("set_amplitude",
             &LFM_Source::set_amplitude,
             py::arg("amplitude"),
             D(LFM_Source, set_amplitude))

        ;
}
