/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(peak_detector_2.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0ac8fbb870bf6e89fd7a8c45eec36552)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lfmTools/peak_detector_2.h>
// pydoc.h is automatically generated in the build directory
#include <peak_detector_2_pydoc.h>

void bind_peak_detector_2(py::module& m)
{

    using peak_detector_2    = gr::lfmTools::peak_detector_2;


    py::class_<peak_detector_2, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<peak_detector_2>>(m, "peak_detector_2", D(peak_detector_2))

        .def(py::init(&peak_detector_2::make),
           D(peak_detector_2,make)
        )
        



        ;




}








