/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(peak_cancel.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(65c620668f3508927e2f8d0db76cd49f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lfmTools/peak_cancel.h>
// pydoc.h is automatically generated in the build directory
#include <peak_cancel_pydoc.h>

void bind_peak_cancel(py::module& m)
{

    using peak_cancel = ::gr::lfmTools::peak_cancel;


    py::class_<peak_cancel,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<peak_cancel>>(m, "peak_cancel", D(peak_cancel))

        .def(py::init(&peak_cancel::make),
             py::arg("bandwidth") = 3.0E+5,
             py::arg("pulse_width") = 1.0E-4,
             py::arg("samp_rate") = 2.0E+6,
             py::arg("key") = "peak",
             D(peak_cancel, make))


        .def("set_bandwidth",
             &peak_cancel::set_bandwidth,
             py::arg("bandwidth"),
             D(peak_cancel, set_bandwidth))


        .def("set_pulse_width",
             &peak_cancel::set_pulse_width,
             py::arg("pulse_width"),
             D(peak_cancel, set_pulse_width))


        .def("set_samp_rate",
             &peak_cancel::set_samp_rate,
             py::arg("samp_rate"),
             D(peak_cancel, set_samp_rate))


        .def("set_key", &peak_cancel::set_key, py::arg("arg0"), D(peak_cancel, set_key))

        ;
}
