/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(peak_detector.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6f628849aca22c8b40eed35e624dcac3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lfmTools/peak_detector.h>
// pydoc.h is automatically generated in the build directory
#include <peak_detector_pydoc.h>

void bind_peak_detector(py::module& m)
{

    using peak_detector = ::gr::lfmTools::peak_detector;


    py::class_<peak_detector,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<peak_detector>>(m, "peak_detector", D(peak_detector))

        .def(py::init(&peak_detector::make),
             py::arg("threshold") = 0.01,
             py::arg("look_ahead") = 100,
             D(peak_detector, make))


        .def("set_threshold",
             &peak_detector::set_threshold,
             py::arg("thres"),
             D(peak_detector, set_threshold))


        .def("set_look_ahead",
             &peak_detector::set_look_ahead,
             py::arg("look"),
             D(peak_detector, set_look_ahead))


        .def("threshold", &peak_detector::threshold, D(peak_detector, threshold))


        .def("look_ahead", &peak_detector::look_ahead, D(peak_detector, look_ahead))

        ;
}
