/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(reset_tagger.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(fa963e7c3c5a2ce61d719762fe197c93)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lfmTools/reset_tagger.h>
// pydoc.h is automatically generated in the build directory
#include <reset_tagger_pydoc.h>

void bind_reset_tagger(py::module& m)
{

    using reset_tagger = ::gr::lfmTools::reset_tagger;


    py::class_<reset_tagger,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<reset_tagger>>(m, "reset_tagger", D(reset_tagger))

        .def(py::init(&reset_tagger::make), py::arg("wait"), D(reset_tagger, make))


        ;
}
