/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tag_advance.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ed3c0f8b075ecfffc2f4aaa9e4ba1be0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lfmTools/tag_advance.h>
// pydoc.h is automatically generated in the build directory
#include <tag_advance_pydoc.h>

void bind_tag_advance(py::module& m)
{

    using tag_advance = ::gr::lfmTools::tag_advance;


    py::class_<tag_advance,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<tag_advance>>(m, "tag_advance", D(tag_advance))

        .def(py::init(&tag_advance::make),
             py::arg("advance_samples"),
             D(tag_advance, make))


        .def("set_advance_samples",
             &tag_advance::set_advance_samples,
             py::arg("advance_samples"),
             D(tag_advance, set_advance_samples))


        .def("advance_samples",
             &tag_advance::advance_samples,
             D(tag_advance, advance_samples))

        ;
}
